import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
        <Head>
          <title>Julias hemsida</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
        <h1 className="text-5xl"> Välkommen till Julias hemsida </h1> 
        <h1>Hej</h1>
        </main>
    </>
  );
};

export default Home;
