import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import nollk from "../images/jaginollkit.png"
import { DM_Serif_Display } from 'next/font/google';
import NavBar from "component/components/navbar";

// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
const dm = DM_Serif_Display({
  variable: '--font-dm',
  subsets: ['latin-ext'],
  weight: "400"
});

const Home: NextPage = () => {
 

  return (
    <>
        <Head>
          <title>Julias hemsida</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />

        </Head>
        <main className={`${dm.variable} font-sans bg-green-bg h-screen min-w-777 overflow-hidden`}>
        <div className="flex flex-row-3 flex-wrap justify-center ml-20">
          <NavBar></NavBar>
          <div className="row-span-1 justify-start grid grid-cols-2">
            <span className=" text-white text-[150px] text-left w-screen font-sans mb-30 ml-20"> Julia </span> 
            <div>M. Sc student in Interaction Design</div>
          </div>
          <div className="row-span-1 justify-start grid grid-cols-2">
            <span className=" text-white text-[150px] text-left w-screen font-sans mt-5 mb-30 ml-20"> Böckert </span> 
            <div className="col-span-1 flex items-center">
              <div className="mt-10">
                <button className="mb-15 border-4 border-black rounded-3xl drop-shadow-xl w-60 h-20 mx-2 text-black text-2xl bg-white">About Me</button>
                <button className="mb-15 rounded-3xl drop-shadow-xl w-60 h-20 mx-2 text-white text-2xl bg-black">Latest Project</button>
              </div>
            </div>
          </div>
          <div className="row-span-1">
            

          </div>
        </div>
        </main>
    </>
  );
};

export default Home;
